# Generated by Django 5.1.5 on 2025-01-29 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Bölmə',
                'verbose_name_plural': 'Bölmələr',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
                ('img', models.URLField(default='https://cdn.dribbble.com/users/755603/screenshots/2592626/sad.gif', verbose_name='Şəkil')),
                ('cate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.categories', verbose_name='Bölmə')),
            ],
            options={
                'verbose_name': 'Məqalə',
                'verbose_name_plural': 'Məqalələr',
            },
        ),
    ]
