# Generated by Django 5.1.5 on 2025-01-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_adverttrendtxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='advertTrendBox',
            field=models.BooleanField(default=False, verbose_name='Trend'),
        ),
    ]
