# Generated by Django 5.1.5 on 2025-01-29 10:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articles_adverttrendtxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='desc',
            field=ckeditor.fields.RichTextField(default='none', verbose_name='Məzmun'),
        ),
    ]
