# Generated by Django 5.1.5 on 2025-01-29 12:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='complated_az',
            field=models.BooleanField(default=False, verbose_name='Təhvil verildi'),
        ),
        migrations.AddField(
            model_name='articles',
            name='complated_en',
            field=models.BooleanField(default=False, verbose_name='Təhvil verildi'),
        ),
        migrations.AddField(
            model_name='articles',
            name='complated_ru',
            field=models.BooleanField(default=False, verbose_name='Təhvil verildi'),
        ),
        migrations.AddField(
            model_name='articles',
            name='desc_az',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='articles',
            name='desc_en',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='articles',
            name='desc_ru',
            field=ckeditor.fields.RichTextField(default='none', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='articles',
            name='sale_az',
            field=models.BooleanField(default=False, verbose_name='Endirim'),
        ),
        migrations.AddField(
            model_name='articles',
            name='sale_en',
            field=models.BooleanField(default=False, verbose_name='Endirim'),
        ),
        migrations.AddField(
            model_name='articles',
            name='sale_ru',
            field=models.BooleanField(default=False, verbose_name='Endirim'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Ad'),
        ),
    ]
