# Generated by Django 5.1.5 on 2025-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_complated_az_articles_complated_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='advertTrendTxt_az',
            field=models.TextField(default='Trend', null=True, verbose_name='Məqalə başlığı Trend üçün'),
        ),
        migrations.AddField(
            model_name='articles',
            name='advertTrendTxt_en',
            field=models.TextField(default='Trend', null=True, verbose_name='Məqalə başlığı Trend üçün'),
        ),
        migrations.AddField(
            model_name='articles',
            name='advertTrendTxt_ru',
            field=models.TextField(default='Trend', null=True, verbose_name='Məqalə başlığı Trend üçün'),
        ),
    ]
