# Generated by Django 5.1.5 on 2025-01-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_adverttrendtxt_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='advertLeftBox',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='advertRightBottomLeftBox',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='advertRightBottomRightBox',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='advertRightTopBox',
        ),
    ]
