# Generated by Django 5.1.5 on 2025-01-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_articles_advertleftbox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='complated_az',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='complated_en',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='complated_ru',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='sale_az',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='sale_en',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='sale_ru',
        ),
    ]
