# Generated by Django 5.1.5 on 2025-01-30 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_articles_complated_az_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='advertTrendBox',
        ),
    ]
